name: Build A20s boot + dtbo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KERNEL_REPO: https://github.com/Guigui357/android_kernel_samsung_a20sxx_old.git
      DEVICE: a20s
      THREADS: 4

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git bc bison flex \
          build-essential \
          gcc-aarch64-linux-gnu \
          libssl-dev libncurses-dev \
          device-tree-compiler \
          android-sdk-libsparse-utils \
          cpio curl zip python3
    
    - name: Clone kernel
      run: |
        git clone --depth=1 $KERNEL_REPO kernel

    - name: Compile kernel
      run: |
        cd kernel
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make a20s_eur_open_defconfig
        scripts/config 
        make -j4 dtboimg bootimg
        scripts/config --disable CONFIG_BT
        scripts/config --disable CONFIG_BT_BCM
        scripts/config --disable CONFIG_BT_HCIBTUSB
        scripts/config --disable CONFIG_BT_HCIUART
        scripts/config --disable CONFIG_BT_BTFM
        scripts/config --disable CONFIG_BT_LE
        scripts/config --disable CONFIG_BT_RFCOMM
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: a20s-kernel-build
        path: |
          kernel/arch/arm64/boot/boot.img
          kernel/arch/arm64/boot/dtbo.img
